# Kocom RS485
- platform: mqtt
  name: "Kocom Livingroom Thermostat"
  mode_state_topic: "kocom/room/thermo/0/state"
  mode_command_topic: "kocom/room/thermo/0/heat_mode/command"
  mode_state_template: "{{ value_json.heat_mode }}"
  temperature_state_topic: "kocom/room/thermo/0/state"
  temperature_command_topic: "kocom/room/thermo/0/set_temp/command"
  temperature_state_template: "{{ value_json.set_temp }}"
  current_temperature_topic: "kocom/room/thermo/0/state"
  current_temperature_template: "{{ value_json.cur_temp }}"
  modes:
    - "off"
    - "heat"
  min_temp: 20
  max_temp: 25
  retain: false
  qos: 0

- platform: mqtt
  name: "Kocom Bedroom Thermostat"
  mode_state_topic: "kocom/room/thermo/1/state"
  mode_command_topic: "kocom/room/thermo/1/heat_mode/command"
  mode_state_template: "{{ value_json.heat_mode }}"
  temperature_state_topic: "kocom/room/thermo/1/state"
  temperature_command_topic: "kocom/room/thermo/1/set_temp/command"
  temperature_state_template: "{{ value_json.set_temp }}"
  current_temperature_topic: "kocom/room/thermo/1/state"
  current_temperature_template: "{{ value_json.cur_temp }}"
  modes:
    - "off"
    - "heat"
  min_temp: 20
  max_temp: 25
  retain: false
  qos: 0

- platform: mqtt
  name: "Kocom Room1 Thermostat"
  mode_state_topic: "kocom/room/thermo/2/state"
  mode_command_topic: "kocom/room/thermo/2/heat_mode/command"
  mode_state_template: "{{ value_json.heat_mode }}"
  temperature_state_topic: "kocom/room/thermo/2/state"
  temperature_command_topic: "kocom/room/thermo/2/set_temp/command"
  temperature_state_template: "{{ value_json.set_temp }}"
  current_temperature_topic: "kocom/room/thermo/2/state"
  current_temperature_template: "{{ value_json.cur_temp }}"
  modes:
    - "off"
    - "heat"
  min_temp: 20
  max_temp: 30
  retain: false
  qos: 0

- platform: mqtt
  name: "Kocom Room2 Thermostat"
  mode_state_topic: "kocom/room/thermo/3/state"
  mode_command_topic: "kocom/room/thermo/3/heat_mode/command"
  mode_state_template: "{{ value_json.heat_mode }}"
  temperature_state_topic: "kocom/room/thermo/3/state"
  temperature_command_topic: "kocom/room/thermo/3/set_temp/command"
  temperature_state_template: "{{ value_json.set_temp }}"
  current_temperature_topic: "kocom/room/thermo/3/state"
  current_temperature_template: "{{ value_json.cur_temp }}"
  modes:
    - "off"
    - "heat"
  min_temp: 20
  max_temp: 25
  retain: false
  qos: 0
