switch: !include switchs.yaml
climate: !include climate.yaml

# Kocom RS485
fan:
  - platform: mqtt
    name: Kocom Wallpad Fan
    command_topic: "kocom/livingroom/fan/command"
    state_topic: "kocom/livingroom/fan/state"
    state_value_template: "{{ value_json.state }}"
    preset_mode_state_topic: "kocom/livingroom/fan/state"
    preset_mode_value_template: "{{ value_json.level }}"
    preset_mode_command_topic: "kocom/livingroom/fan/set_preset_mode/command"
    preset_mode_command_template: "{{ value }}"
    preset_modes:
      - "0"
      - "1"
      - "2"
      - "3"
    payload_on: "on"
    payload_off: "off"
    qos: 0

light:
  - platform: mqtt
    name: Kocom Livingroom Light1
    command_topic: "kocom/livingroom/light/1/command"
    state_topic: "kocom/livingroom/light/state"
    state_value_template: "{{ value_json.light_1 }}"
    payload_on: "on"
    payload_off: "off"
    qos: 0
  
  - platform: mqtt
    name: Kocom Livingroom Light2
    command_topic: "kocom/livingroom/light/2/command"
    state_topic: "kocom/livingroom/light/state"
    state_value_template: "{{ value_json.light_2 }}"
    payload_on: "on"
    payload_off: "off"
    qos: 0
