---
name: Bridge Server
version: 2023.11.09
slug: edgebridge
description: Bridge Server for SmartThings Edge drivers
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/clipman/HomeAssistant
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/edgebridge.cfg 설정파일: true
schema:
  share/edgebridge.cfg 설정파일: bool
