---
name: Bridge Server
version: 2023.11.10
slug: edgebridge
description: Bridge Server for SmartThings Edge drivers
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/clipman/HomeAssistant
map:
  - share:rw
ports:
  8088/tcp: 8088
options:
  share/edgebridge/edgebridge.cfg 설정파일: true
schema:
  share/edgebridge/edgebridge.cfg 설정파일: bool
startup: system
init: false
