---
name: Kocom Call with RS485
version: 2022.04.10
slug: kocom_call
description: Kocom Call for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/clipman/addons
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom/kocom_call.conf 설정파일: true
schema:
  share/kocom/kocom_call.conf 설정파일: bool
