# Kocom RS485
- platform: mqtt
  name: Kocom Home Call
  command_topic: "kocom/myhome/home_call/command"
  state_topic: "kocom/myhome/home_call/state"
  value_template: "{{ value_json.state }}"
  payload_on: "on"
  payload_off: "off"
  qos: 0

- platform: mqtt
  name: Kocom Gate Call
  command_topic: "kocom/myhome/gate_call/command"
  state_topic: "kocom/myhome/gate_call/state"
  value_template: "{{ value_json.state }}"
  payload_on: "on"
  payload_off: "off"
  qos: 0
